### ISSUE TITLE
javlibrary接口调用出错

### ISSUE THREAD

**Issue by mengx8** [junerain123/javsdt#21]
```
GET http://www.r40z.com/cn/vl_searchbyid.php?keyword=CHN-123
第1个失败！打开javlibrary搜索页面失败：http://www.r40z.com/cn/vl_searchbyid.php?keyword=CHN-123，\\CHN-123-C.mp4
```
```
Traceback (most recent call last):
  File "F:\download\V1.0.1.JAVSDT\V1.0.1_javsdt_191220\youma_javlibrary.py", line 388, in <module>
    jav_html = get_jav_html(jav_list)
  File "F:\download\V1.0.1.JAVSDT\V1.0.1_javsdt_191220\youma_javlibrary.py", line 78, in get_jav_html
    rqs = requests.get(url_list[0],timeout=10, headers=headers)
  File "C:\Users\mengx8\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\mengx8\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\mengx8\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mengx8\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mengx8\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
```

**Comment by babylife** [comment]
修改ini文件，替换www.r40z.com ， 该域名当前无法正常使用，具体换哪个就不方便说了
